version: '3.1'
services:
  app:
    container_name: crud-accenture
    image: crud-accenture
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_crud_accenture