version: '3.1'
services:
  app:
    container_name: crud-accenture
    image: crud-accenture
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - pg
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crud-accenture